apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alertmanager-alertmanager.yaml
  - alertmanager-service.yaml
  - alertmanager-serviceMonitor.yaml
  - alertmanager-secret.yaml
  - alertmanager-serviceAccount.yaml
  - alertmanager-ingress.yaml
  - prometheus-rules-alertmanager.yaml

namespace: monitoring
