apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  alerting:
    alertmanagers:
      - namespace: zcp-system
        name: alertmanager
        port: http
  baseImage: "prom/prometheus"
  paused: false
  replicas: 1
  logLevel: info
  routePrefix: "/"
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  ruleSelector: {}
  ruleNamespaceSelector: {}
  resources:
    requests:
      memory: 1Gi
  enableAdminAPI: true
  retention: 15d
  scrapeInterval: 10s
  evaluationInterval: 10s
  version: "v2.7.0"
  securityContext:
    runAsUser: 0
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: standard
        resources:
          requests:
            storage: 20Gi
