apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus-prometheus.yaml
  - prometheus-service.yaml
  - prometheus-ingress.yaml
  - prometheus-clusterRole.yaml
  - prometheus-clusterRoleBinding.yaml
  - prometheus-serviceAccount.yaml
  - prometheus-rules-prometheus.yaml
  - prometheus-serviceMonitor.yaml
  - additional-scrape-configs.yaml

namespace: monitoring
