apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: "prometheus"
    prometheus: cluster
  name: rule-prometheus 
spec:
  groups:
    - name: prometheus.rules
      rules:
        - alert: PrometheusFailedReload
          expr: prometheus_config_last_reload_successful == 0
          for: 10m
          labels:
            channel: sk-cps-ops
            severity: critical
          annotations:
            summary: Prometheus configuration reload has failed 
            description: Reloading Prometheus' configuration has failed for {{ $labels.namespace}}/{{ $labels.pod}}.
        - alert: PrometheusErrorSendingAlerts
          expr: rate(prometheus_notifications_errors_total[5m]) / rate(prometheus_notifications_sent_total[5m]) > 0.01
          for: 10m
          labels:
            channel: sk-cps-ops
            severity: critical
          annotations:
            summary: Errors while sending alerts from Prometheus
            description: Errors while sending alerts from Prometheus to Alertmanager {{$labels.Alertmanager}}
        - alert: PrometheusNotConnectedtoAlertmanagers
          expr: prometheus_notifications_alertmanagers_discovered < 1
          for: 10m
          labels:
            channel: sk-cps-ops
            severity: critical
          annotations:
            summary: Prometheus is not connected to any Alertmanagers
            description: Prometheus is not connected to any Alertmanagers
