namespace: zcp-system

resources:
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  - rules.yaml

generatorOptions:
  disableNameSuffixHash: true 

configMapGenerator:
- name: blackbox-exporter-config
  files:
  - configs/blackbox.yml

