apiVersion: v1
kind: Service
metadata:
  name: blackbox
  namespace: kube-system
  labels:
    app: blackbox-exporter
  annotations:
    prometheus.io/scrape: "false"
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9115
      targetPort: 9115
      protocol: TCP
  selector:
    app: blackbox-exporter 
