apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  labels:
    app: node-exporter
  namespace: kube-system
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: metrics
      port: 9100
      targetPort: metrics
      protocol: TCP
  selector:
    app: node-exporter
