apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: kube-system 
  annotations:
    prometheus.io/scrape: 'false'
  labels:
    component: grafana 
spec:
  #type: NodePort
  ports:
    - name: grafana 
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    component: grafana

